// packages/react/demo/index.tsx
import * as React from "react";
import * as ReactDOM from "react-dom";
import { FileUploader } from "../dist/";

class Main extends React.Component<{}, {}> {
    private locale = null;
    private name = "test";
    private url = "http://localhost:9997";
    private method = "POST";

    componentWillMount() {
        if (navigator.language === "zh-CN") {
            import("../../core/dist/locales/" + navigator.language + ".js").then(module => {
                this.locale = module.locale;
                this.setState({ locale: this.locale });
            });
        }
    }

    render() {
        return (
            <div style={{ margin: "10px", width: "800px" }}>
                <a href="https://github.com/plantain-00/file-uploader-component/tree/master/packages/react/demo" target="_blank">the source code of the demo</a>
                <h3>just get the file or blob object and print it at console</h3>
                <FileUploader fileGot={this.fileGot}
                    accept="image/*"
                    multiple={true}
                    locale={this.locale}>
                </FileUploader>
                <h3>upload the file to server</h3>
                name:
                <input type="text" defaultValue={this.name} onChange={e => this.name = e.currentTarget.value} />
                url:
                <input type="text" defaultValue={this.url} onChange={e => this.url = e.currentTarget.value} />
                method:
                <input type="text" defaultValue={this.method} onChange={e => this.method = e.currentTarget.value} />
                <FileUploader fileUploaded={this.fileUploaded}
                    fileGot={this.fileGot}
                    accept="image/*"
                    multiple={true}
                    locale={this.locale}
                    name={this.name}
                    url={this.url}
                    method={this.method}>
                </FileUploader>
            </div>
        );
    }

    private fileGot(response: any) {
        // tslint:disable-next-line:no-console
        console.log(response);
    }
    private fileUploaded(file: File | Blob) {
        // tslint:disable-next-line:no-console
        console.log(file);
    }
}

ReactDOM.render(<Main />, document.getElementById("container"));

// packages/angular/demo/main.component.ts
import { Component } from "@angular/core";

@Component({
    selector: "app",
    template: `
    <div style="margin: 10px; width: 800px">
        <a href="https://github.com/plantain-00/file-uploader-component/tree/master/packages/angular/demo" target="_blank">the source code of the demo</a>
        <h3>just get the file or blob object and print it at console</h3>
        <file-uploader (fileGot)="fileGot($event)"
            accept="image/*"
            multiple="true"
            [locale]="locale">
        </file-uploader>
        <h3>upload the file to server</h3>
        name:
        <input type="text" [(ngModel)]="name"/>
        url:
        <input type="text" [(ngModel)]="url"/>
        method:
        <input type="text" [(ngModel)]="method"/>
        <file-uploader (fileUploaded)="fileUploaded($event)"
            (fileGot)="fileGot($event)"
            accept="image/*"
            multiple="true"
            [locale]="locale"
            [name]="name"
            [url]="url"
            [method]="method">
        </file-uploader>
    </div>
    `,
})
export class MainComponent {
    locale = null;
    name = "test";
    url = "http://localhost:9997";
    method = "POST";
    ngOnInit() {
        if (navigator.language === "zh-CN") {
            import("../../core/dist/locales/" + navigator.language + ".js").then(module => {
                this.locale = module.locale;
            });
        }
    }
    fileGot(response: any) {
        // tslint:disable-next-line:no-console
        console.log(response);
    }
    fileUploaded(file: File | Blob) {
        // tslint:disable-next-line:no-console
        console.log(file);
    }
}
