// packages/angular/src/index.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core'
import * as common from 'file-uploader-component'
import { indexTemplateHtml } from './variables'

/**
 * @public
 */
@Component({
  selector: 'file-uploader',
  template: indexTemplateHtml
})
export class FileUploaderComponent {
  @Input()
    accept?: string
  @Input()
    multiple?: boolean
  @Input()
    locale?: common.Locale
  @Input()
    name?: string
  @Input()
    url?: string
  @Input()
    method?: string

  @Output()
    fileGot = new EventEmitter<File | Blob>()
  @Output()
    fileUploaded = new EventEmitter<any>()

  get localeObject () {
    return common.getLocale(this.locale)
  }

  requests: common.UploadRequest[] = []

  onDrop (e: DragEvent) {
    common.onDrop(e, this.name, this.url, this.method, file => {
      this.fileGot.emit(file)
    }, request => {
      this.fileUploaded.emit(request.response)
      common.removeRequest(this.requests, request)
    }, percent => {
            // nothing to do
    }, request => {
      this.requests.push(request)
    })
  }
  onPaste (e: ClipboardEvent) {
    common.onPaste(e, this.name, this.url, this.method, file => {
      this.fileGot.emit(file)
    }, request => {
      this.fileUploaded.emit(request.response)
      common.removeRequest(this.requests, request)
    }, percent => {
            // nothing to do
    }, request => {
      this.requests.push(request)
    })
  }
  onFileUploaded (e: Event) {
    common.onFileUploaded(e, this.name, this.url, this.method, file => {
      this.fileGot.emit(file)
    }, request => {
      this.fileUploaded.emit(request.response)
      common.removeRequest(this.requests, request)
    }, percent => {
            // nothing to do
    }, request => {
      this.requests.push(request)
    })
  }

  trackBy (request: common.UploadRequest, index: number) {
    return index
  }
}

// packages/react/src/index.tsx
import * as React from "react";

import * as common from "file-uploader-component";
export * from "file-uploader-component";

/**
 * @public
 */
export type Props = {
    accept?: string;
    multiple?: boolean;
    locale?: common.Locale | null
    name?: string;
    url?: string;
    method?: string;
    fileGot?: (file: File | Blob) => void;
    fileUploaded?: (response: any) => void;
};

/**
 * @public
 */
export class FileUploader extends React.Component<Props, {}> {
    private requests: common.UploadRequest[] = [];

    render() {
        const locale = common.getLocale(this.props.locale);
        const progress = this.requests.map((request, i) => (
            <div className="file-uploader-progress" title={(request.file as File).name} key={i}>
                <div style={{ width: request.percent + "%" }}>{request.percent}%</div>
            </div>
        ));
        return (
            <div onDrop={(e: React.DragEvent<HTMLElement> | DragEvent) => { this.onDrop(e as DragEvent); }}
                onPaste={(e: React.ClipboardEvent<HTMLElement> | ClipboardEvent) => { this.onPaste(e as ClipboardEvent); }}>
                {progress}
                <p className="file-uploader-container">
                    {locale.dragAndDrop}
                    <span>{locale.selectFile}</span>
                    {locale.pasteFromClipboard}
                    <input type="file"
                        multiple={this.props.multiple}
                        accept={this.props.accept}
                        onChange={(e: React.FormEvent<HTMLElement> | Event) => { this.onFileUploaded(e as Event); }} />
                </p>
            </div>
        );
    }

    private onDrop(e: DragEvent) {
        common.onDrop(e, this.props.name, this.props.url, this.props.method, file => {
            if (this.props.fileGot) {
                this.props.fileGot(file);
            }
        }, request => {
            if (this.props.fileUploaded) {
                this.props.fileUploaded(request.response);
            }
            common.removeRequest(this.requests, request);
            this.setState({ requests: this.requests });
        }, percent => {
            this.setState({ requests: this.requests });
        }, request => {
            this.requests.push(request);
        });
    }
    private onPaste(e: ClipboardEvent) {
        common.onPaste(e, this.props.name, this.props.url, this.props.method, file => {
            if (this.props.fileGot) {
                this.props.fileGot(file);
            }
        }, request => {
            if (this.props.fileUploaded) {
                this.props.fileUploaded(request.response);
            }
            common.removeRequest(this.requests, request);
            this.setState({ requests: this.requests });
        }, percent => {
            this.setState({ requests: this.requests });
        }, request => {
            this.requests.push(request);
        });
    }
    private onFileUploaded(e: Event) {
        common.onFileUploaded(e, this.props.name, this.props.url, this.props.method, file => {
            if (this.props.fileGot) {
                this.props.fileGot(file);
            }
        }, request => {
            if (this.props.fileUploaded) {
                this.props.fileUploaded(request.response);
            }
            common.removeRequest(this.requests, request);
            this.setState({ requests: this.requests });
        }, percent => {
            this.setState({ requests: this.requests });
        }, request => {
            this.requests.push(request);
        });
    }
}
